# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61179e231d9e5f776fe41fcd28fb4eaaba96c6d9fb87a99e0a259b2ac178187fad27df98a3a25415af5d4dc1dca547fdfd842975535f47b760b828f111115154

test:
  secret_key_base: 810e9fe1ef2ae4c27e6a9361a479516c50004ff3335b430ce8d57ef60b1c93a915f4f58beaa5db35dd87f490ea2cf36b8f023894cb137c53ddca7a18f34f84d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
